name: fooddelivery
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  get: 4.6.5
  http: ^0.13.5
  logger: ^1.2.2
  shrink_sidemenu: ^2.0.0+2-null-safety
  skeletons: ^0.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
